### ISSUE TITLE
Duplicate Proofs?

### ISSUE THREAD

**Issue by ddubick** [GalactechsLLC/dg_fast_farmer#19]
Hi there, I'm using the GH version of Evergreen FastFarmer so I'm not sure if this is appropriate here but it seems to be a problem with the farmer part so I'll post this here and hope.
I just got a notification about duplicate proofs (image attached).  It would seem that I got a proof and then about 30 seconds later FF tried submitting the same proof again two more times.
While one instance of this doesn't concern me greatly my difficulty is at 20000 and with the upcoming plot filter reduction I'm worried that FF might be doing unnecessary work calculating duplicates.
Just thought I'd bring this to your attention in case there's a deeper problem (or delete if this isn't the correct place for Evergreen FastFarmer support).
Thank you.
![image](https://github.com/GalactechsLLC/dg_fast_farmer/assets/60245747/eff45d7c-490e-4886-afe5-960c3901a026)
![image](https://github.com/GalactechsLLC/dg_fast_farmer/assets/60245747/7cd145cb-6eee-4b2c-9ef8-bf4c5b3feca5)

**Comment by ddubick** [comment]
I guess I didn't notice that the duplicate only took 0.2s to process.  So I guess there's probably not a concern that duplicates would be bogging down the system.

**Comment by spacefarmers** [comment]
Sometimes the network sends signage points multiple times. When this happens, your farmer will find multiple proofs, which the pool then rejects as duplicates. This is a common occurrence. The farmer might have used a cache to process them, so it didn't cause much troubles. However, I don't know FastFarmer good enough to be certain.

![image](https://github.com/GalactechsLLC/dg_fast_farmer/assets/97022238/292963aa-70c7-411d-af20-d9974ded2b0c)
_Total pool duplicates (gray) at that time. I found your farmer, 11pm in my timezone is 3pm in your timezone._

**Comment by ddubick** [comment]
> Sometimes the network sends signage points multiple times. When this happens, your farmer will find multiple proofs, which the pool then rejects as duplicates. This is a common occurrence. The farmer might have used a cache to process them, so it didn't cause much troubles. However, I don't know FastFarmer good enough to be certain.
> 
> ![image](https://private-user-images.githubusercontent.com/97022238/336714413-292963aa-70c7-411d-af20-d9974ded2b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTg5NTUsIm5iZiI6MTcxNzYxODY1NSwicGF0aCI6Ii85NzAyMjIzOC8zMzY3MTQ0MTMtMjkyOTYzYWEtNzBjNy00MTFkLWFmMjAtZDk5NzRkZWQyYjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIwMTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMjc3NGY5NTExMTZhNzk3YmQ3YmFkZTEwZTYyMTQ5YjExNGNjNTY3NjhkOTI4NjUyODRhNzZjNjliZjI0ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQJhc51SZJooes2VyM97aJDU4HU_Mk7pmTs3dQ_o_NI) _Total pool duplicates (gray) at that time. I found your farmer, 11pm in my timezone is 3pm in your timezone._

So a whole bunch of other farmers submitted duplicates during that hour?  Interesting.  Okay I won't worry about it then.
